repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use latest stable version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use latest stable version
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0  # Use latest stable version
    hooks:
      - id: prettier
        files: "\\.(js|jsx|ts|tsx|json|md|html|css|scss)$"

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.0.0
  #   hooks:
  #     - id: eslint
  #       files: "\\.(js|jsx|ts|tsx)$"
  #       minimum_pre_commit_version: "2.9.0"  # Add this as a string
