name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: PR Auto-assign
        uses: cam3ron2/pr-auto-assign@latest
        with:
          reviewers: technoinformals, Better-Stay-Unknown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add this line
